Repository taskcluster/taskgraph, pull requests merged in 2023-12, with the labels that each got.

#372 refactor!: rename 'job' transforms to 'run'
  docs/concepts/kind.rst
  docs/concepts/loading.rst
  docs/concepts/task-graphs.rst
  docs/concepts/transforms.rst
  docs/howto/create-tasks.rst
  docs/howto/use-fetches.rst
  docs/reference/migrations.rst
  docs/reference/source/taskgraph.transforms.rst
  docs/reference/source/taskgraph.transforms.run.rst
  docs/reference/transforms/from_deps.rst
  docs/tutorials/creating-a-task-graph.rst
  pyproject.toml
  src/taskgraph/create.py
  src/taskgraph/decision.py
  src/taskgraph/loader/default.py
  src/taskgraph/transforms/base.py
  src/taskgraph/transforms/code_review.py
  src/taskgraph/transforms/fetch.py
  src/taskgraph/transforms/from_deps.py
  src/taskgraph/transforms/run/__init__.py
  src/taskgraph/transforms/run/common.py
  src/taskgraph/transforms/run/index_search.py
  src/taskgraph/transforms/run/run_task.py
  src/taskgraph/transforms/run/toolchain.py
  src/taskgraph/transforms/task.py
  src/taskgraph/transforms/task_context.py
  src/taskgraph/util/schema.py
  src/taskgraph/util/treeherder.py
  taskcluster/ci/codecov/kind.yml
  taskcluster/ci/doc/kind.yml
  taskcluster/ci/fetch/kind.yml
  taskcluster/ci/tests/kind.yml
  test/test_generator.py
  test/test_transforms_run.py
  test/test_transforms_run_run_task.py
  test/test_transforms_run_toolchain.py
Labels: BREAKING CHANGE

#375 Re-name taskcluster/ci to taskcluster/kinds and move config.yml to taskcluster/
  docs/howto/create-tasks.rst
  docs/howto/docker.rst
  docs/index.rst
  docs/reference/migrations.rst
  docs/tutorials/creating-a-task-graph.rst
  src/taskgraph/config.py
  src/taskgraph/generator.py
  src/taskgraph/util/docker.py
  taskcluster/config.yml
  taskcluster/kinds/codecov/kind.yml
  taskcluster/kinds/doc/kind.yml
  taskcluster/kinds/docker-image/kind.yml
  taskcluster/kinds/fetch/kind.yml
  taskcluster/kinds/tests/kind.yml
  template/{{cookiecutter.project_name}}/taskcluster/config.yml
  template/{{cookiecutter.project_name}}/taskcluster/kinds/docker-image/kind.yml
  template/{{cookiecutter.project_name}}/taskcluster/kinds/hello/kind.yml
  test/data/taskcluster/config.yml
  test/fixtures/gen.py
  test/test_main.py
  test/test_morph.py
Labels: documentation, BREAKING CHANGE, CI, python

#378 refactor!: remove 'release_notifications' backward compat shim
  src/taskgraph/transforms/__init__.py
  test/test_transforms_notify.py
Labels: BREAKING CHANGE

#376 refactor!: change 'root_dir' to point to main 'taskcluster' directory
  src/taskgraph/config.py
  src/taskgraph/generator.py
  test/fixtures/gen.py
  test/test_morph.py
Labels: BREAKING CHANGE

#394 test: add tests for cached_task transforms and utility file
  test/fixtures/gen.py
  test/test_transforms_cached_tasks.py
  test/test_util_cached_tasks.py
Labels: CI
